/**
 * Stage-specific items — farklı aşamalar ve ürün tipleri için ayrı öneriler.
 * Her madde bir stage tag taşır (stage-0-100, stage-growth, vb.) ve product tag (web, mobile, data, universal).
 */
import type { StrategyItem } from '../types/strategy';

export const STAGE_ITEMS: StrategyItem[] = [
  // ----- PRE-LAUNCH -----
  {
    id: 'pre-ship-readiness',
    title: 'Ship readiness checklist',
    description: 'Final checks before going live: env vars, feature flags, error handling.',
    actionSteps: ['Lock production config', 'Disable dev-only features', 'Smoke test critical path'],
    tags: ['stage-pre-launch', 'universal', 'production'],
    priority: 'critical',
    domain: 'production',
  },
  {
    id: 'pre-first-deploy-web',
    title: 'First production deploy (web)',
    description: 'Deploy to production; verify URL, SSL, and core flows.',
    actionSteps: ['Deploy to hosting', 'Check HTTPS', 'Test signup and login'],
    tags: ['stage-pre-launch', 'web', 'production'],
    priority: 'critical',
    domain: 'production',
  },
  {
    id: 'pre-first-build-mobile',
    title: 'First store build (mobile)',
    description: 'Create a build ready for TestFlight or Play internal testing.',
    actionSteps: ['Archive / build release', 'Upload to TestFlight or Play', 'Install and smoke test'],
    tags: ['stage-pre-launch', 'mobile', 'production'],
    priority: 'critical',
    domain: 'production',
  },
  {
    id: 'pre-beta-list',
    title: 'Build a small beta list',
    description: 'Get 10–20 people ready to try the product on day one.',
    actionSteps: ['List 20 potential testers', 'Send invite link', 'Set expectation for feedback'],
    tags: ['stage-pre-launch', 'universal', 'launch'],
    priority: 'high',
    domain: 'launch',
  },
  {
    id: 'pre-data-pipeline-ready',
    title: 'First pipeline or dataset ready',
    description: 'One reliable pipeline or core dataset that stakeholders can use.',
    actionSteps: ['Document source and schedule', 'Run once successfully', 'Share one output'],
    tags: ['stage-pre-launch', 'data', 'production'],
    priority: 'critical',
    domain: 'production',
  },

  // ----- JUST LAUNCHED -----
  {
    id: 'just-first-10-users',
    title: 'Get your first 10 users',
    description: 'Focus on one channel and get 10 real people to sign up or install.',
    actionSteps: ['Pick one channel (Twitter, PH, community)', 'Share personally', 'Follow up for feedback'],
    tags: ['stage-just-launched', 'universal', 'growth'],
    priority: 'critical',
    domain: 'growth',
  },
  {
    id: 'just-feedback-loop',
    title: 'Set up a simple feedback loop',
    description: 'One way to collect feedback: form, chat, or email.',
    actionSteps: ['Add feedback button or form', 'Check responses weekly', 'Reply to every message'],
    tags: ['stage-just-launched', 'universal', 'retention'],
    priority: 'high',
    domain: 'retention',
  },
  {
    id: 'just-web-landing',
    title: 'Landing page and one CTA',
    description: 'Clear value prop and one signup or waitlist CTA.',
    actionSteps: ['Write headline and 2–3 bullets', 'Single CTA button', 'Track clicks or signups'],
    tags: ['stage-just-launched', 'web', 'distribution'],
    priority: 'high',
    domain: 'distribution',
  },
  {
    id: 'just-mobile-store-draft',
    title: 'App store listing draft',
    description: 'Draft title, short description, and at least one screenshot.',
    actionSteps: ['Write app name and short description', 'One screenshot per key screen', 'Save as draft'],
    tags: ['stage-just-launched', 'mobile', 'distribution'],
    priority: 'high',
    domain: 'distribution',
  },
  {
    id: 'just-data-first-dashboard',
    title: 'One stakeholder dashboard',
    description: 'One dashboard or report that one team actually uses.',
    actionSteps: ['Pick one use case', 'Build one view', 'Share and iterate'],
    tags: ['stage-just-launched', 'data', 'analytics'],
    priority: 'high',
    domain: 'analytics',
  },

  // ----- 0-100 USERS -----
  {
    id: '0-100-one-channel',
    title: 'Double down on one acquisition channel',
    description: 'Pick the channel that brought your first users and do more of it.',
    actionSteps: ['Identify best channel so far', '2–3 concrete actions this week', 'Measure signups from it'],
    tags: ['stage-0-100', 'universal', 'growth'],
    priority: 'critical',
    domain: 'growth',
  },
  {
    id: '0-100-power-user-talks',
    title: 'Talk to 5 power users',
    description: 'Interview users who use the product most; find what they love and what’s missing.',
    actionSteps: ['List 5 active users', 'Schedule 20-min calls', 'Note 3 improvements'],
    tags: ['stage-0-100', 'universal', 'retention'],
    priority: 'critical',
    domain: 'retention',
  },
  {
    id: '0-100-simple-analytics',
    title: 'Simple analytics: who does what',
    description: 'Know how many users, and one key action they take.',
    actionSteps: ['Track DAU or weekly active', 'One “key action” event', 'Check weekly'],
    tags: ['stage-0-100', 'universal', 'analytics'],
    priority: 'high',
    domain: 'analytics',
  },
  {
    id: '0-100-web-seo-one-keyword',
    title: 'SEO: one focus keyword',
    description: 'Optimize one page for one keyword and submit sitemap.',
    actionSteps: ['Pick one keyword', 'Optimize title and meta', 'Submit sitemap to Search Console'],
    tags: ['stage-0-100', 'web', 'growth'],
    priority: 'high',
    domain: 'growth',
  },
  {
    id: '0-100-mobile-aso-basics',
    title: 'ASO basics: title and screenshots',
    description: 'Improve app store title and at least 3 screenshots.',
    actionSteps: ['A/B test title or subtitle', '3 screenshots with benefit text', 'Update and monitor'],
    tags: ['stage-0-100', 'mobile', 'distribution'],
    priority: 'high',
    domain: 'distribution',
  },
  {
    id: '0-100-data-quality-rules',
    title: 'Define 3 data quality rules',
    description: 'Simple rules: freshness, completeness, or one validation.',
    actionSteps: ['Pick 3 critical checks', 'Document and run manually', 'Alert on failure'],
    tags: ['stage-0-100', 'data', 'analytics'],
    priority: 'high',
    domain: 'analytics',
  },
  {
    id: '0-100-email-welcome',
    title: 'Welcome email sequence',
    description: 'One welcome email that explains the next step.',
    actionSteps: ['Write one welcome email', 'Send within 5 min of signup', 'Add one “next step” CTA'],
    tags: ['stage-0-100', 'universal', 'retention'],
    priority: 'medium',
    domain: 'retention',
  },

  // ----- 100-1000 USERS -----
  {
    id: '100-1000-scale-channel',
    title: 'Scale the channel that works',
    description: 'Invest more in the channel that drives signups; set a weekly goal.',
    actionSteps: ['Confirm best channel from data', 'Set weekly signup goal', 'Increase effort or spend'],
    tags: ['stage-100-1000', 'universal', 'growth'],
    priority: 'critical',
    domain: 'growth',
  },
  {
    id: '100-1000-first-paid',
    title: 'First paid or monetization test',
    description: 'Test willingness to pay: price page, trial, or one paid feature.',
    actionSteps: ['Add pricing or paywall', 'Track conversion', 'Interview 3 who paid'],
    tags: ['stage-100-1000', 'universal', 'monetization'],
    priority: 'high',
    domain: 'monetization',
  },
  {
    id: '100-1000-web-content-scale',
    title: 'Content: 3 pieces that convert',
    description: 'Publish 3 pieces (blog, docs, or use cases) tied to signup.',
    actionSteps: ['Pick 3 topics', 'Publish and link to product', 'Track signups from content'],
    tags: ['stage-100-1000', 'web', 'growth'],
    priority: 'high',
    domain: 'growth',
  },
  {
    id: '100-1000-mobile-push',
    title: 'Push notifications for retention',
    description: 'One useful push: re-engage or nudge to key action.',
    actionSteps: ['Define one push trigger', 'Write copy and send', 'Measure open and action'],
    tags: ['stage-100-1000', 'mobile', 'retention'],
    priority: 'high',
    domain: 'retention',
  },
  {
    id: '100-1000-data-self-serve',
    title: 'Self-serve access or docs',
    description: 'Let one more team or customer use data without you.',
    actionSteps: ['Document how to access', 'One example query or report', 'Collect feedback'],
    tags: ['stage-100-1000', 'data', 'distribution'],
    priority: 'high',
    domain: 'distribution',
  },
  {
    id: '100-1000-churn-survey',
    title: 'Churn or cancellation survey',
    description: 'Ask why users leave; fix top 1–2 reasons.',
    actionSteps: ['Add exit survey', 'Categorize reasons', 'Address #1 cause'],
    tags: ['stage-100-1000', 'universal', 'retention'],
    priority: 'high',
    domain: 'retention',
  },

  // ----- GROWTH (1k+ scaling acquisition) -----
  {
    id: 'growth-cac-payback',
    title: 'Measure CAC and payback',
    description: 'Know cost per signup and how long until you break even.',
    actionSteps: ['Calculate CAC by channel', 'Estimate LTV or revenue per user', 'Compare payback'],
    tags: ['stage-growth', 'universal', 'growth'],
    priority: 'critical',
    domain: 'growth',
  },
  {
    id: 'growth-paid-scale',
    title: 'Scale paid acquisition',
    description: 'Increase spend on the channel that works; optimize creatives and audience.',
    actionSteps: ['Increase budget on best channel', 'Test 2–3 creatives', 'Track CPA and quality'],
    tags: ['stage-growth', 'universal', 'distribution'],
    priority: 'high',
    domain: 'distribution',
  },
  {
    id: 'growth-web-seo-scale',
    title: 'SEO: 5 key pages and keywords',
    description: 'Optimize 5 pages for 5 keywords; track rankings.',
    actionSteps: ['Pick 5 pages and keywords', 'Optimize titles and content', 'Track in Search Console'],
    tags: ['stage-growth', 'web', 'growth'],
    priority: 'high',
    domain: 'growth',
  },
  {
    id: 'growth-mobile-store-campaign',
    title: 'App store campaigns (UA)',
    description: 'Run Apple Search Ads or Google UAC with a clear goal.',
    actionSteps: ['Set campaign goal', 'Create ad group and keywords', 'Measure installs and cost'],
    tags: ['stage-growth', 'mobile', 'distribution'],
    priority: 'high',
    domain: 'distribution',
  },
  {
    id: 'growth-data-api-docs',
    title: 'Data API and developer docs',
    description: 'Document data API so more consumers can integrate.',
    actionSteps: ['OpenAPI or docs', 'Examples and auth', 'Onboard one new consumer'],
    tags: ['stage-growth', 'data', 'distribution'],
    priority: 'high',
    domain: 'distribution',
  },
  {
    id: 'growth-expansion-revenue',
    title: 'Expansion revenue (upsell)',
    description: 'Upsell or cross-sell to existing users.',
    actionSteps: ['List upgrade triggers', 'Add in-app prompt', 'Track expansion MRR'],
    tags: ['stage-growth', 'universal', 'monetization'],
    priority: 'high',
    domain: 'monetization',
  },

  // ----- SCALING -----
  {
    id: 'scale-reliability-sla',
    title: 'Uptime target and monitoring',
    description: 'Set an uptime target and alert when you miss it.',
    actionSteps: ['Define SLA (e.g. 99.5%)', 'Set up uptime checks', 'Alert and runbook'],
    tags: ['stage-scaling', 'universal', 'production'],
    priority: 'critical',
    domain: 'scaling',
  },
  {
    id: 'scale-cost-control',
    title: 'Cost visibility and alerts',
    description: 'Track infra and tooling cost; set a budget alert.',
    actionSteps: ['Tag resources', 'Dashboard or export', 'Monthly review'],
    tags: ['stage-scaling', 'universal', 'monetization'],
    priority: 'high',
    domain: 'scaling',
  },
  {
    id: 'scale-support-scale',
    title: 'Support at scale',
    description: 'FAQ, docs, or tiered support so you don’t bottleneck.',
    actionSteps: ['Document top 5 questions', 'Add FAQ or help center', 'Define escalation path'],
    tags: ['stage-scaling', 'universal', 'scaling'],
    priority: 'high',
    domain: 'scaling',
  },
  {
    id: 'scale-web-perf',
    title: 'Web performance and Core Web Vitals',
    description: 'Improve LCP, FID, CLS; monitor in production.',
    actionSteps: ['Measure CWV', 'Fix biggest issue', 'Set budget in CI'],
    tags: ['stage-scaling', 'web', 'scaling'],
    priority: 'high',
    domain: 'scaling',
  },
  {
    id: 'scale-mobile-crash-rate',
    title: 'Crash rate and stability',
    description: 'Get crash-free rate above 99%; fix top crashes.',
    actionSteps: ['Track crash-free rate', 'Fix top 2 crashes', 'Release and verify'],
    tags: ['stage-scaling', 'mobile', 'production'],
    priority: 'high',
    domain: 'scaling',
  },
  {
    id: 'scale-data-lineage',
    title: 'Data lineage and governance',
    description: 'Document pipelines and access so scaling is safe.',
    actionSteps: ['Document key pipelines', 'Define roles', 'One audit pass'],
    tags: ['stage-scaling', 'data', 'risk'],
    priority: 'high',
    domain: 'risk',
  },

  // ----- PLATEAU -----
  {
    id: 'plateau-retention-deep-dive',
    title: 'Retention deep dive',
    description: 'Find why users leave and fix the main leak.',
    actionSteps: ['Cohort by signup week', 'Identify drop-off step', 'Test one fix'],
    tags: ['stage-plateau', 'universal', 'retention'],
    priority: 'critical',
    domain: 'retention',
  },
  {
    id: 'plateau-survey-churn',
    title: 'Churn survey and interviews',
    description: 'Ask churned users why they left; prioritize fixes.',
    actionSteps: ['Send churn survey', 'Interview 5', 'List top 3 reasons'],
    tags: ['stage-plateau', 'universal', 'retention'],
    priority: 'critical',
    domain: 'retention',
  },
  {
    id: 'plateau-activation',
    title: 'Improve activation rate',
    description: 'Get more users to “aha” in the first session or week.',
    actionSteps: ['Define activation event', 'Measure % who activate', 'Shorten path'],
    tags: ['stage-plateau', 'universal', 'retention'],
    priority: 'high',
    domain: 'retention',
  },
  {
    id: 'plateau-ab-test',
    title: 'One A/B test on signup or core flow',
    description: 'Test one change that could improve conversion or retention.',
    actionSteps: ['Pick one metric', 'Run test', 'Ship winner'],
    tags: ['stage-plateau', 'universal', 'optimization'],
    priority: 'high',
    domain: 'optimization',
  },

  // ----- PIVOTING -----
  {
    id: 'pivot-analytics-review',
    title: 'Review what the data says',
    description: 'Look at usage, retention, and revenue; decide what to keep or drop.',
    actionSteps: ['Pull key metrics', 'Identify weak areas', 'List hypotheses'],
    tags: ['stage-pivoting', 'universal', 'analytics'],
    priority: 'critical',
    domain: 'analytics',
  },
  {
    id: 'pivot-user-interviews',
    title: 'Interview 10 users about direction',
    description: 'Ask if they’d use a different focus or feature set.',
    actionSteps: ['Recruit 10 users', 'Ask about problems and alternatives', 'Synthesize themes'],
    tags: ['stage-pivoting', 'universal', 'retention'],
    priority: 'critical',
    domain: 'retention',
  },
  {
    id: 'pivot-one-bet',
    title: 'Pick one bet and validate',
    description: 'Choose one new direction and validate with minimal build.',
    actionSteps: ['Choose one bet', 'Define validation (survey, MVP)', 'Run and decide'],
    tags: ['stage-pivoting', 'universal', 'growth'],
    priority: 'high',
    domain: 'growth',
  },
];
