import { GeneratedChecklist, Priority } from '../types';
import * as Sharing from 'expo-sharing';
import { cacheDirectory, writeAsStringAsync, EncodingType } from 'expo-file-system/legacy';

const PRIORITY_EMOJI: Record<Priority, string> = {
    critical: '🔴',
    high: '🟠',
    medium: '🟡',
    low: '🟢',
};

const PHASE_LABELS: Record<string, string> = {
    planning: 'Planning',
    coding: 'Development',
    testing: 'Testing',
    deployment: 'Deployment',
    scaling: 'Scaling & Growth',
};

export function generateMarkdown(checklist: GeneratedChecklist): string {
    const completed = checklist.items.filter(i => i.completed).length;
    const total = checklist.items.length;
    const progress = total > 0 ? Math.round((completed / total) * 100) : 0;
    const date = new Date(checklist.createdAt).toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric',
    });

    const progressBar = buildProgressBar(progress);

    const grouped: Record<Priority, typeof checklist.items> = {
        critical: [],
        high: [],
        medium: [],
        low: [],
    };
    for (const item of checklist.items) {
        grouped[item.priority].push(item);
    }

    let md = `# ${checklist.title}\n\n`;
    md += `> **Phase:** ${PHASE_LABELS[checklist.phase] ?? checklist.phase}  \n`;
    md += `> **Tech Stack:** ${checklist.techStack.join(', ') || 'N/A'}  \n`;
    md += `> **Created:** ${date}  \n`;
    if (checklist.goal) md += `> **Goal:** ${checklist.goal}  \n`;
    md += `\n`;

    md += `## Progress\n\n`;
    md += `${progressBar} **${progress}%** (${completed}/${total} tasks completed)\n\n`;
    md += `---\n\n`;

    const priorities: Priority[] = ['critical', 'high', 'medium', 'low'];
    for (const priority of priorities) {
        const items = grouped[priority];
        if (items.length === 0) continue;

        md += `## ${PRIORITY_EMOJI[priority]} ${capitalize(priority)} Priority\n\n`;
        for (const item of items) {
            const checkbox = item.completed ? '[x]' : '[ ]';
            md += `- ${checkbox} **${item.title}**\n`;
            if (item.description) {
                md += `  > ${item.description}\n`;
            }
            if (item.notes) {
                md += `  > 📝 *Note: ${item.notes}*\n`;
            }
            md += `\n`;
        }
    }

    md += `---\n\n`;
    md += `*Generated by [DevChecklist](https://apps.apple.com/app/devchecklist)*\n`;

    return md;
}

export async function exportChecklistAsMarkdown(checklist: GeneratedChecklist): Promise<void> {
    const md = generateMarkdown(checklist);
    const filename = `${checklist.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_checklist.md`;
    const fileUri = `${cacheDirectory}${filename}`;

    await writeAsStringAsync(fileUri, md, { encoding: EncodingType.UTF8 });

    const isAvailable = await Sharing.isAvailableAsync();
    if (isAvailable) {
        await Sharing.shareAsync(fileUri, {
            mimeType: 'text/markdown',
            dialogTitle: `Export: ${checklist.title}`,
            UTI: 'net.daringfireball.markdown',
        });
    }
}

function buildProgressBar(progress: number): string {
    const filled = Math.round(progress / 10);
    const empty = 10 - filled;
    return `[${'█'.repeat(filled)}${'░'.repeat(empty)}]`;
}

function capitalize(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
}
