import React, { useState, useMemo } from 'react';
import { View, Text, StyleSheet, Pressable, Modal, ScrollView, TextInput, Alert } from 'react-native';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import * as Clipboard from 'expo-clipboard';
import { useThemeStore } from '../../store/themeStore';
import { GeneratedChecklist } from '../../types';

const ONE_DAY_MS = 24 * 60 * 60 * 1000;

interface StandupData {
    yesterday: string[];
    today: string[];
}

function generateStandup(checklists: GeneratedChecklist[]): StandupData {
    const now = Date.now();
    const yesterday: string[] = [];
    const today: string[] = [];

    for (const checklist of checklists) {
        for (const item of checklist.items) {
            if (item.completed && item.completedAt && now - item.completedAt < ONE_DAY_MS) {
                yesterday.push(item.title);
            }
        }
        // Next 3 incomplete items as today's plan
        const incomplete = checklist.items.filter(i => !i.completed);
        for (const item of incomplete.slice(0, 3)) {
            if (today.length < 5) today.push(item.title);
        }
    }

    return { yesterday, today };
}

function formatStandupText(standup: StandupData, blocker: string, projectName: string): string {
    let text = `📋 *Daily Standup — ${new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric' })}*\n`;
    text += `🏗️ *Project: ${projectName}*\n\n`;

    text += `✅ *Yesterday:*\n`;
    if (standup.yesterday.length > 0) {
        standup.yesterday.forEach(t => { text += `  • ${t}\n`; });
    } else {
        text += `  • No completed tasks recorded\n`;
    }

    text += `\n🎯 *Today:*\n`;
    if (standup.today.length > 0) {
        standup.today.forEach(t => { text += `  • ${t}\n`; });
    } else {
        text += `  • Review checklist and pick next tasks\n`;
    }

    if (blocker.trim()) {
        text += `\n🚧 *Blockers:*\n  • ${blocker.trim()}\n`;
    }

    text += `\n_Generated by DevChecklist_`;
    return text;
}

interface StandupGeneratorProps {
    checklists: GeneratedChecklist[];
    projectName: string;
}

export function StandupGenerator({ checklists, projectName }: StandupGeneratorProps) {
    const { colorMode } = useThemeStore();
    const isDark = colorMode === 'dark';
    const [visible, setVisible] = useState(false);
    const [blocker, setBlocker] = useState('');
    const [copied, setCopied] = useState(false);

    const textPrimary = isDark ? '#e2e8f0' : '#0f172a';
    const textMuted = isDark ? '#64748b' : '#94a3b8';
    const cardBg = isDark ? 'rgba(255,255,255,0.04)' : '#ffffff';
    const cardBorder = isDark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.07)';
    const modalBg = isDark ? '#0f0d1a' : '#ffffff';
    const inputBg = isDark ? 'rgba(255,255,255,0.06)' : '#f8fafc';
    const inputBorder = isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)';

    const standup = useMemo(() => generateStandup(checklists), [checklists]);
    const standupText = useMemo(() => formatStandupText(standup, blocker, projectName), [standup, blocker, projectName]);

    const handleCopy = async () => {
        await Clipboard.setStringAsync(standupText);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <>
            <Pressable
                onPress={() => setVisible(true)}
                style={[styles.triggerBtn, { backgroundColor: cardBg, borderColor: cardBorder }]}
            >
                <MaterialCommunityIcons name="clipboard-text-clock-outline" size={18} color="#60a5fa" />
                <Text style={[styles.triggerText, { color: textPrimary }]}>Daily Standup</Text>
                <MaterialCommunityIcons name="chevron-right" size={16} color={textMuted} />
            </Pressable>

            <Modal visible={visible} transparent animationType="slide" onRequestClose={() => setVisible(false)}>
                <Pressable style={styles.overlay} onPress={() => setVisible(false)} />
                <View style={[styles.sheet, { backgroundColor: modalBg }]}>
                    <View style={styles.handle} />
                    <View style={styles.sheetHeader}>
                        <MaterialCommunityIcons name="clipboard-text-clock-outline" size={22} color="#60a5fa" />
                        <Text style={[styles.sheetTitle, { color: textPrimary }]}>Daily Standup</Text>
                    </View>

                    <ScrollView showsVerticalScrollIndicator={false}>
                        {/* Yesterday */}
                        <Text style={[styles.sectionLabel, { color: textMuted }]}>✅ YESTERDAY</Text>
                        {standup.yesterday.length > 0 ? (
                            standup.yesterday.map((t, i) => (
                                <View key={i} style={styles.taskRow}>
                                    <View style={[styles.dot, { backgroundColor: '#22c55e' }]} />
                                    <Text style={[styles.taskText, { color: textPrimary }]}>{t}</Text>
                                </View>
                            ))
                        ) : (
                            <Text style={[styles.emptyNote, { color: textMuted }]}>No tasks completed in the last 24h</Text>
                        )}

                        {/* Today */}
                        <Text style={[styles.sectionLabel, { color: textMuted }]}>🎯 TODAY</Text>
                        {standup.today.length > 0 ? (
                            standup.today.map((t, i) => (
                                <View key={i} style={styles.taskRow}>
                                    <View style={[styles.dot, { backgroundColor: '#60a5fa' }]} />
                                    <Text style={[styles.taskText, { color: textPrimary }]}>{t}</Text>
                                </View>
                            ))
                        ) : (
                            <Text style={[styles.emptyNote, { color: textMuted }]}>No upcoming tasks found</Text>
                        )}

                        {/* Blocker */}
                        <Text style={[styles.sectionLabel, { color: textMuted }]}>🚧 BLOCKERS (optional)</Text>
                        <TextInput
                            style={[styles.blockerInput, { backgroundColor: inputBg, borderColor: inputBorder, color: textPrimary }]}
                            placeholder="Any blockers or issues?"
                            placeholderTextColor={textMuted}
                            value={blocker}
                            onChangeText={setBlocker}
                            multiline
                        />
                    </ScrollView>

                    <Pressable
                        style={[styles.copyBtn, { backgroundColor: copied ? '#22c55e' : '#1d4ed8' }]}
                        onPress={handleCopy}
                    >
                        <MaterialCommunityIcons
                            name={copied ? 'check' : 'content-copy'}
                            size={18}
                            color="white"
                        />
                        <Text style={styles.copyBtnText}>{copied ? 'Copied!' : 'Copy to Clipboard'}</Text>
                    </Pressable>
                </View>
            </Modal>
        </>
    );
}

const styles = StyleSheet.create({
    triggerBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        padding: 14,
        borderRadius: 14,
        borderWidth: 1,
        marginBottom: 12,
    },
    triggerText: { flex: 1, fontSize: 14, fontWeight: '600' },
    overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)' },
    sheet: { padding: 24, borderTopLeftRadius: 28, borderTopRightRadius: 28, maxHeight: '85%' },
    handle: { width: 40, height: 4, borderRadius: 2, backgroundColor: '#374151', alignSelf: 'center', marginBottom: 20 },
    sheetHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 20 },
    sheetTitle: { fontSize: 20, fontWeight: 'bold' },
    sectionLabel: { fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 8, marginTop: 16 },
    taskRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, marginBottom: 8 },
    dot: { width: 8, height: 8, borderRadius: 4, marginTop: 5 },
    taskText: { flex: 1, fontSize: 14, lineHeight: 20 },
    emptyNote: { fontSize: 13, fontStyle: 'italic', marginBottom: 8 },
    blockerInput: {
        borderWidth: 1, borderRadius: 12,
        padding: 12, fontSize: 14, minHeight: 60,
        textAlignVertical: 'top', marginBottom: 8,
    },
    copyBtn: {
        flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
        gap: 8, borderRadius: 14, height: 52, marginTop: 16,
    },
    copyBtnText: { color: 'white', fontWeight: 'bold', fontSize: 16 },
});
